export {default as ServicePage} from "./ServicesPage/ServicesPage"
export {default as ContactPage} from "./ContactPage/ContactPage"
export {default as BusOptionsPage} from "./BusOptionsPage/BusOptionsPage"
export {default as LandingPage} from "./LandingPage/LandingPage"
export {default as AboutPage} from "./AboutPage/AboutPage"